name: dynwgraphs_env
channels:
  - defaults
dependencies:
  - numpy
  - matplotlib
  - scipy
  - pandas
  - pytorch
  - click
variables:
  MLFLOW_TRACKING_URI: to_be_set_to_preferred_path_to_store_mlflow_tracking